"""Add template model

Revision ID: 1328d0f22789
Revises: 
Create Date: 2023-07-05 09:39:18.257219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1328d0f22789"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("templates")
    # ### end Alembic commands ###
